version: "3.8"
services:
  mongo:
    image: mongo:latest
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    command: mongod --auth
    ports:
      - 27017:27017
    volumes:
      - mongodbvol:/data/db
  backend:
    build: ./backend
    env_file: ./.env
    environment:
      - DB_HOST=mongo
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE_NAME   
      - PORT=9000
    ports:
        - 9000:9000
    depends_on:
      - mongo
    restart: always
  frontend:
    build: ./frontend
    ports:
        - 3000:3000
    depends_on:
      - mongo
      - backend
volumes:
  mongodbvol:

